### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by zhangdahua1** [siemens/powergym#2]
Thanks for this PowerGym provided by the author. This is very useful to me. But as a novice in programming, there are still some difficulties to understand. Can the author upload a simple supporting training algorithm to help me learn？

Thank you very much if you can reply.

**Comment by zhangdahua1** [comment]
Also would you send it to my email?

**Comment by zhangdahua1** [comment]
There is another question for you to answer. Why does running the random_agent file multiple times get the same result?

**Comment by bruinWang** [comment]
@zhangdahua1 thanks for your interest to powergym. This repo is for environment, not for control algorithms.  To get some quick results, you may consider a PPO agent run on 13-bus system.
