### ISSUE TITLE
How to handle change in distribution system after training?

### ISSUE THREAD

**Issue by sahasubhajit** [siemens/powergym#5]
I was going through the paper "PowerGym: A Reinforcement Learning Environment for Volt-Var Control in Power Distribution Systems" again! The reinforcement learning allows to enable online training which is an advantage of the model I guess. But I was wondering what would be the solution if we add or remove components like bus, voltage regulator, capacitor bank to the trained power distribution system.  
My Idea: Say there is an addition of load bus. We will simulate it's active power and reactive power and concatenate this data to the historical data of the remaining distribution system.  Then train the model with additional load bus.  We can hope that this would not effect the overall performance badly. Such simulation can be made for the controller devices also, like we consider to had that capacitor bank at the historical data and start training. While training the AI will turn the switch on or off the load bus. And finally we will learn to operate such devices.

Kindly, tell me if my idea is promising or not. It would be helpful if you please share your thoughts regarding this issue.

**Comment by bruinWang** [comment]
Removing element is a great idea. It opens up the environment for tasks as such restoration and shedding. For example, taking a load off can mimic the load shedding. You are invited to develop this feature. Let me know how that sounds to you.

**Comment by sahasubhajit** [comment]
Thanks for your sharing your thoughts. I think we can do the same thing if we consider to turn on a circuit breaker to isolate a load bus (zero active and reactive power).

**Comment by sahasubhajit** [comment]
Thanks for sharing your valuable thoughts. I think we can do similar training for fault condition. Like if there is a sudden fault at the line connecting two buses. The circuit breaker will isolate that output bus and there will be no current flow at the output bus. Consequently the KVA power at the second bus will also be 0 (by P=VI) i.e. KW = 0,  KVAr = 0 at the second bus.  So I think setting the active and reactive power as zero at a load bus would mimic fault condition. Is not it?  It may cause to rise in PU voltage at that isolated bus and I think the voltage regulator at the generator bus would reduce generator bus voltage. It would reduce slightly the over-rising voltage at the isolated bus voltage.

**Comment by bruinWang** [comment]
Sorry for my late response. Yes, I think this quick mitigation is totally possible. However, when it scales up, it can become quite problematic. For example, if you have a feeder, A1--A2--...--An. Assuming the source/substation is at A1, and you have loads connected to A2 all the way to An, named after L2, L3... Ln. If something happens to the line A1--A2, you will have to zero for all L2, L3, ..., Ln. This is of course an extreme case, however, you can see the complexity under some extreme scenarios. 

That is why I suggest directly openning a line. The OpenDSS command is just one line "Lines.A12 bus1=A1 bus2=A2 enabled=n".
